<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Authors>Mehdi Farokh Tabar</Authors>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/m-farokhtabar/MFT.BuildingBlocks</RepositoryUrl>
		<PackageId>MFT.BuildingBlocks.Domain</PackageId>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Description>Reusable Clean Architecture / DDD building blocks for .NET.</Description>
	</PropertyGroup>

</Project>
